version: '3'
services:

  gateway-api:
    image: gateway-api
    container_name: gateway-api
    build: gateway_api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis-event-bus

      

  store-service:
    image: store-service
    container_name: store-service
    build: store_service
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis-event-bus
      - redis-store-service


  redis-event-bus:
    container_name: redis-event-bus
    image: redis
    ports:
      - "6379:6379"

  redis-store-service:
    container_name: redis-store-service
    image: redis
    ports:
      - "6381:6379"
      
volumes:
  logvolume01: {}
networks:
  default:
    name: comp3122-project
