version: '3'
services:

  gateway-api:
    image: gateway-api
    container_name: gateway-api
    build: gateway_api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis-event-bus

  store-service:
    image: store-service
    container_name: store-service
    build: store_service
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis-event-bus
      - redis-store-service
      - redis-menu-service

  menu-service:
    image: menu-service
    container_name: menu-service
    build: menu_service
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis-event-bus
      - redis-order-service
      - redis-store-service

  order-service:
    image: order-service
    container_name: order-service
    build: order_service
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis-event-bus
      - redis-order-service
      
  authentication-service:
    image: authentication-service
    container_name: authentication-service
    build:
      context: ./authentication_service
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis-event-bus
      - redis-authentication-service

  redis-event-bus:
    container_name: redis-event-bus
    image: redis
    ports:
      - "6379:6379"

  redis-order-service:
    container_name: redis-order-service
    image: redis
    ports:
      - "6380:6379"

  redis-store-service:
    container_name: redis-store-service
    image: redis
    ports:
      - "6381:6379"

  redis-menu-service:
    container_name: redis-menu-service
    image: redis
    ports:
      - "6382:6379"

  redis-authentication-service:
    container_name: redis-authentication-service
    image: redis
    ports:
      - "6383:6379"

volumes:
  logvolume01: {}
networks:
  default:
    name: comp3122-project