version: '3'
services:
  gateway-api:
    image: gateway-api
    container_name: gateway-api
    build: gateway_api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis
  order-service:
    image: order-service
    container_name: order-service
    build: order_service
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  logvolume01: {}
networks:
  default:
    name: comp3122-project