global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

  #metric exporter of the machine
  - job_name: 'nodeExporter'
    static_configs:
    - targets: ['nodeExporter:9100']

  #metric exporter of the python app
  - job_name: 'store-service'
    metrics_path: /store-metrics
    static_configs:
    - targets: ['store-service:5000']

  #metric exporter of the python app
  - job_name: 'order-service'
    metrics_path: /order-metrics
    static_configs:
    - targets: ['order-service:5000']

    #metric exporter of the python app
  - job_name: 'menu-service'
    metrics_path: /menu-metrics
    static_configs:
    - targets: ['menu-service:5000']